#############################
# Docker machine states
#############################
build:
    docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

state:
	docker-compose ps
